<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $keywords = [
            'karangan bunga duka cita',
            'karangan bunga bandung',
            'karangan bunga wisuda',
            'karangan bunga turut berduka cita',
            'karangan bunga setnov',
            'karangan bunga pernikahan',
            'karangan bunga ucapan selamat',
            'karangan bunga lucu',
            'karangan bunga ulang tahun',
            'karangan bunga semarang',
            'karangan bunga',
            'karangan bunga anniversary',
            'karangan bunga adalah',
            'karangan bunga anies',
            'karangan bunga anggrek',
            'karangan bunga asli',
            'karangan bunga aliano',
            'karangan bunga akreditasi',
            'karangan bunga berduka cita',
            'karangan bunga belasungkawa',
            'karangan bunga bogor',
            'karangan bunga balai kota',
            'karangan bunga buat wisuda',
            'karangan bunga buat pacar',
            'karangan bunga berbentuk lingkaran',
            'karangan bunga buat mantan',
            'karangan bunga bekasi',
            'karangan bunga cirebon',
            'karangan bunga cikarang',
            'karangan bunga cinta',
            'karangan bunga congratulation',
            'karangan bunga cilacap',
            'karangan bunga cibubur',
            'karangan bunga cimahi',
            'karangan bunga ciamis',
            'karangan bunga cibinong',
            'karangan bunga ciptaan taufik ismail',
            'karangan bunga di bandung',
            'karangan bunga duka',
            'karangan bunga duka cita bandung',
            'karangan bunga di cirebon',
            'karangan bunga digital',
            'karangan bunga dari kain flanel',
            'karangan bunga doraemon',
            'karangan bunga di solo',
            'karangan bunga di cikarang',
            'tulisan di karangan bunga',
            'ucapan di karangan bunga',
            'karangan bunga di palembang',
            'karangan bunga english',
            'karangan bunga edelweis',
            'karangan bunga aster',
            'karangan eksposisi bunga',
            'karangan bunga muara enim',
            'karangan bunga pernikahan elegan',
            'karangan bunga pernikahan emas',
            'edit karangan bunga',
            'karangan bunga duka cita in english',
            'karangan bunga flanel',
            'karangan bunga fadli',
            'karangan bunga florist',
            'florist karangan bunga',
            'karangan bunga foto',
            'karangan bunga florist bandung',
            'karangan bunga florist jakarta',
            'karangan bunga dari flanel',
            'usaha karangan bunga florist',
            'karangan bunga grand opening',
            'karangan bunga gubernur',
            'karangan bunga graduation',
            'karangan bunga gubernur jakarta',
            'karangan bunga gading serpong',
            'karangan bunga gokil',
            'karangan bunga garut',
            'karangan bunga gubernur baru',
            'karangan bunga gubernur dki',
            'karangan bunga gresik',
            'karangan bunga hut',
            'karangan bunga happy wedding',
            'karangan bunga harga',
            'karangan bunga hut bri',
            'karangan bunga hut tni',
            'karangan bunga hari ibu',
            'karangan bunga hut brimob',
            'karangan bunga hut pgri',
            'karangan bunga hari guru',
            'karangan bunga hari pahlawan',
            'karangan bunga indah',
            'karangan bunga ikut berduka cita',
            'karangan bunga inggris',
            'karangan bunga in english',
            'karangan bunga indonesia',
            'karangan bunga indramayu',
            'karangan bunga image',
            'karangan bunga taufik ismail',
            'karangan bunga bahasa inggris',
            'karangan bunga karya taufik ismail',
            'karangan bunga jakarta',
            'karangan bunga jogja',
            'karangan bunga jakarta selatan',
            'karangan bunga jambi',
            'karangan bunga jarot',
            'karangan bunga jakarta timur',
            'karangan bunga jakarta pusat',
            'karangan bunga jepara',
            'karangan bunga jakarta barat',
            'karangan bunga jombang',
            'karangan bunga kematian',
            'karangan bunga khas hawaii',
            'karangan bunga kocak',
            'karangan bunga kecil',
            'karangan bunga khas hawaii disebut',
            'karangan bunga klaten',
            'karangan bunga kosong',
            'karangan bunga kertas',
            'karangan bunga khitanan',
            'karangan bunga lampung',
            'karangan bunga love',
            'karangan bunga lucu anis',
            'karangan bunga lingkaran',
            'karangan bunga lucu wisuda',
            'karangan bunga lucu anis sandi',
            'karangan bunga lucu untuk anis',
            'karangan bunga lepas sambut',
            'karangan bunga meninggal',
            'karangan bunga makassar',
            'karangan bunga meja',
            'karangan bunga medan',
            'karangan bunga mawar untuk pacar',
            'karangan bunga malang',
            'karangan bunga mawar putih',
            'karangan bunga melati',
            'karangan bunga magelang',
            'karangan bunga manado',
            'karangan bunga natal',
            'karangan bunga nikahan',
            'karangan bunga nikah lucu',
            'karangan bunga nusantara',
            'karangan bunga nama lain',
            'karangan bunga nyeleneh',
            'karangan bunga ngawi',
            'karangan bunga nganjuk',
            'karangan bunga nikah',
            'karangan bunga nikahan lucu',
            'karangan bunga orang meninggal',
            'karangan bunga online',
            'karangan bunga orang mati',
            'karangan bunga online jakarta',
            'karangan bunga online bandung',
            'karangan bunga oleh taufik ismail',
            'karangan bunga orang sakit',
            'karangan bunga online palembang',
            'karangan bunga 2018',
            'karangan bunga online surabaya',
            'karangan bunga papan',
            'karangan bunga puisi',
            'karangan bunga png',
            'karangan bunga pelantikan',
            'karangan bunga palembang',
            'karangan bunga purwakarta',
            'karangan bunga padang',
            'karangan bunga pengantin',
            'karangan bunga purwokerto',
            'dp karangan bunga duka cita',
            'dp karangan bunga',
            'dp karangan bunga lucu',
            'dp karangan bunga duka',
            'dp karangan bunga turut berduka cita',
            'gambar dp karangan bunga',
            'dp bbm karangan bunga',
            'dp bbm karangan bunga duka cita',
            'dp bbm karangan bunga lucu',
            'dp bbm karangan bunga kematian',
            'karangan bunga romantis',
            'karangan bunga rip',
            'karangan bunga rusak',
            'karangan bunga rscm',
            'karangan bunga rawamangun',
            'karangan bunga rawa belong',
            'karangan bunga rumah baru',
            'karangan bunga rembang',
            'karangan bunga ros',
            'karangan bunga selamat',
            'karangan bunga surabaya',
            'karangan bunga solo',
            'karangan bunga sukabumi',
            'karangan bunga selamat ulang tahun',
            'karangan bunga serah terima jabatan',
            'karangan bunga sederhana',
            'karangan bunga tiang listrik',
            'karangan bunga tasikmalaya',
            'karangan bunga terindah',
            'karangan bunga tts',
            'karangan bunga tegal',
            'karangan bunga tangerang',
            'karangan bunga tangan',
            'karangan bunga terdekat',
            'karangan bunga untuk setnov',
            'karangan bunga untuk ahok',
            'karangan bunga untuk wisuda',
            'karangan bunga ucapan selamat ulang tahun',
            'karangan bunga ucapan',
            'karangan bunga unik',
            'karangan bunga untuk pernikahan',
            'karangan bunga ucapan selamat wisuda',
            'karangan bunga vektor',
            'karangan bunga valentine',
            'karangan bunga vas',
            'karangan bunga vintage',
            'karangan bunga untuk valentine',
            'gambar karangan bunga vektor',
            'video karangan bunga',
            'jual karangan bunga valentine',
            'karangan bunga wisuda unik',
            'karangan bunga wonogiri',
            'karangan bunga wedding',
            'karangan bunga wisuda lucu',
            'karangan bunga wastu kencana bandung',
            'karangan bunga wisuda pacar',
            'karangan bunga wonosobo kabupaten wonosobo jawa tengah',
            'karangan bunga wonosari',
            'karangan bunga wastukencana',
            'karangan bunga yogyakarta',
            'karangan bunga yang dirusak',
            'karangan bunga yang indah',
            'karangan bunga yang dirusak untuk setnov',
            'karangan bunga yang rusak',
            'karangan bunga yang berbentuk lingkaran',
            'karangan bunga yang cantik',
            'karangan bunga yang lucu',
            'karangan bunga yg d rusak',
            'karangan bunga yg indah',
            'karangan bunga ziarah',
            'karangan bunga untuk ziarah',
            'karangan bunga 1 miliar',
            'karangan bunga 1m',
            'karangan bunga 1 milyar',
            'karangan bunga 24 jam',
            'karangan bunga 2015',
            'karangan bunga jakarta 24 jam',
            'pesan karangan bunga 24 jam',
            'harga karangan bunga 2015',
            'puisi 3 karangan bunga',
            'karangan bunga liputan 6',
            '7 karangan bunga tergokil',
            'karangan bunga',
            'karangan bunga bandung',
            'karangan bunga di bandung',
            'jual karangan bunga di bandung',
            'jual karangan bunga bandung',
            'beli karangan bunga di bandung',
            'beli karangan bunga bandung',
            'karangan bunga cimahi',
            'karangan bunga di cimahi',
            'jual karangan bunga di cimahi',
            'jual karangan bunga cimahi',
            'beli karangan bunga di cimahi',
            'beli karangan bunga cimahi',
            'karangan bunga sumedang',
            'karangan bunga di sumedang',
            'jual karangan bunga di sumedang',
            'jual karangan bunga sumedang',
            'beli karangan bunga di sumedang',
            'beli karangan bunga sumedang',
            'karangan bunga majalengka',
            'karangan bunga di majalengka',
            'jual karangan bunga di majalengka',
            'jual karangan bunga majalengka',
            'beli karangan bunga di majalengka',
            'beli karangan bunga majalengka',
            'karangan bunga ciamis',
            'karangan bunga di ciamis',
            'jual karangan bunga di ciamis',
            'jual karangan bunga ciamis',
            'beli karangan bunga di ciamis',
            'beli karangan bunga ciamis',
            'karangan bunga tasikmalaya',
            'karangan bunga di tasikmalaya',
            'jual karangan bunga di tasikmalaya',
            'jual karangan bunga tasikmalaya',
            'beli karangan bunga di tasikmalaya',
            'beli karangan bunga tasikmalaya',
            'karangan bunga cibiru',
            'karangan bunga di cibiru',
            'jual karangan bunga di cibiru',
            'jual karangan bunga cibiru',
            'beli karangan bunga di cibiru',
            'beli karangan bunga cibiru',
            'karangan bunga cibiru',
            'karangan bunga di cileunyi',
            'jual karangan bunga di cileunyi',
            'jual karangan bunga cileunyi',
            'beli karangan bunga di cileunyi',
            'beli karangan bunga cileunyi',
            'karangan bunga di cililin',
            'jual karangan bunga di cililin',
            'jual karangan bunga cililin',
            'beli karangan bunga di cililin',
            'beli karangan bunga cililin',
            'karangan bunga di baleendah',
            'jual karangan bunga di baleendah',
            'jual karangan bunga baleendah',
            'beli karangan bunga di baleendah',
            'beli karangan bunga baleendah',
            'karangan bunga di bojongsoang',
            'jual karangan bunga di bojongsoang',
            'jual karangan bunga bojongsoang',
            'beli karangan bunga di bojongsoang',
            'beli karangan bunga bojongsoang',
            'karangan bunga di ciwastra',
            'jual karangan bunga di ciwastra',
            'jual karangan bunga ciwastra',
            'beli karangan bunga di ciwastra',
            'beli karangan bunga ciwastra',
            'karangan bunga di margacinta',
            'jual karangan bunga di margacinta',
            'jual karangan bunga margacinta',
            'beli karangan bunga di margacinta',
            'beli karangan bunga margacinta',
            'karangan bunga di gedebage',
            'jual karangan bunga di gedebage',
            'jual karangan bunga gedebage',
            'beli karangan bunga di gedebage',
            'beli karangan bunga gedebage',
            'karangan bunga di soekarno hatta',
            'jual karangan bunga di soekarno hatta',
            'jual karangan bunga soekarno hatta',
            'beli karangan bunga di soekarno hatta',
            'beli karangan bunga soekarno hatta',
            'karangan bunga di buahbatu',
            'jual karangan bunga di buahbatu',
            'jual karangan bunga buahbatu',
            'beli karangan bunga di buahbatu',
            'beli karangan bunga buahbatu',
            'karangan bunga di dago',
            'jual karangan bunga di dago',
            'jual karangan bunga dago',
            'beli karangan bunga di dago',
            'beli karangan bunga dago',
            'karangan bunga di gatsu',
            'jual karangan bunga di gatsu',
            'jual karangan bunga gatsu',
            'beli karangan bunga di gatsu',
            'beli karangan bunga gatsu',
        ];

        // Looping untuk memasukkan data ke dalam database menggunakan DB facade
        foreach ($keywords as $keyword) {
            DB::table('keywords')->insert([
                'keyword' => $keyword,
                'page' => 'Beranda',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
